debug: false
server:
  port: 12138
  servlet:
    context-path: /accountmanager
spring:
  application:
    name: account-manager
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:D:/account-manager/h2db
#    username: root
#    password: h2database
#aes:
#  key: FKVfce6Hjgti2Htu/Sa4iTatTHkHJQxh