debug: false
server:
  port: 12138
  servlet:
    context-path: /accountmanager
spring:
  application:
    name: account-manager
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
---
#开发时使用命令行参数激活dev配置 --spring.profiles.active=dev
debug: true
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:file:D:/h2db
    username: root
    password: h2database
  jpa:
    # 打印sql语句
    show-sql: true
aes:
  key: FKVfce6Hjgti2Htu/Sa4iTatTHkHJQxh
logging:
  config: classpath:log4j2-spring-dev.xml