#命令行参数激活对应环境的配置： --spring.profiles.active=dev
debug: false
maven:
  version: @version@
  package-time: @timestamp@
server:
  port: 12138
  servlet:
    context-path: /accountmanager
spring:
  application:
    name: account-manager
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    initialization-mode: always
    schema:
      - classpath:db/init.sql
    url: jdbc:h2:file:${am.file-path}
    username: root
    password: h2database
    hikari:
      connection-timeout: 2000
#      idle-timeout: 120000
      maximum-pool-size: 10
      max-lifetime: 60000
---
#开发环境，使用内存数据库
debug: true
spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
    url: jdbc:h2:mem:${am.file-path}
am:
  security-key: pq+Sjkd1We1wW44Yz4mN6Q==
  password-digits: 10
  file-path: memTestDB
  backup-path: E:/backupTestDB
logging:
  config: classpath:log4j2-spring-dev.xml
---
#模拟环境，使用文件数据库
spring:
  config:
    activate:
      on-profile:
        - mock
server:
  port: 12139
am:
  security-key: pq+Sjkd1We1wW44Yz4mN6Q==
  password-digits: 10
  file-path: E:/fileTestDB