debug: false
maven:
  version: @version@
  package-time: @timestamp@
server:
  port: 12138
  servlet:
    context-path: /accountmanager
spring:
  application:
    name: account-manager
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    # url: jdbc:h2:file:D:/h2db 文件数据库
---
#开发时使用命令行参数激活dev配置 --spring.profiles.active=dev
debug: true
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:h2db
    username: root
    password: h2database
  jpa:
    # 打印sql语句
    show-sql: false
am:
  security-key: 43CF686405DC1ED8760D7DEBE1AD614A
#  password-digits: 10
logging:
  config: classpath:log4j2-spring-dev.xml